# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from django.contrib import admin

#
class Global_VarAdmin(admin.ModelAdmin):
	model = Global_Var

	verbose_name = 'Global Var'
	verbose_name_plural = 'Global Vars'

	inlines = ()
	
	
	list_display = ('name', )
	search_fields = ['name', ]

#
class Global_Var_CategoryAdmin(admin.ModelAdmin):
	model = Global_Var_Category

	verbose_name = 'Global Var Category'
	verbose_name_plural = 'Global Var Categories'

	inlines = ()
	
	
	list_display = ('name', )
	search_fields = ['name', ]

#
class Global_Var_TypeAdmin(admin.ModelAdmin):
	model = Global_Var_Type

	verbose_name = 'Global Var Type'
	verbose_name_plural = 'Global Var Types'

	inlines = ()
	
	
	list_display = ('name', )
	search_fields = ['name', ]

#
