# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from admin_generic import *
from admin_custom import *
from django.contrib import admin


#
admin.site.register(Global_Var, Global_VarAdmin)
admin.site.register(Global_Var_Category, Global_Var_CategoryAdmin)
admin.site.register(Global_Var_Type, Global_Var_TypeAdmin)
