# Authors: Geoffroy Noel, King's College London, 2009-2020
#
# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.models import User
from admin_generic import *
from admin_custom import *


#
admin.site.register(Version, VersionAdmin)
admin.site.register(Text_Attribute, Text_AttributeAdmin)
admin.site.register(Glossary_Term, Glossary_TermAdmin)
admin.site.register(Work, WorkAdmin)
admin.site.register(Commentary, CommentaryAdmin)
admin.site.register(Folio_Image, Folio_ImageAdmin)
admin.site.register(Bibliographic_Entry, Bibliographic_EntryAdmin)
admin.site.register(Manuscript, ManuscriptAdmin)
admin.site.register(Edition, EditionAdmin)
#admin.site.register(Witness_Transcription, Witness_TranscriptionAdmin)
#admin.site.register(Witness_Translation, Witness_TranslationAdmin)
admin.site.register(Edition_Translation, Edition_TranslationAdmin)
admin.site.register(Witness, WitnessAdmin)
admin.site.register(Editor, EditorAdmin)
admin.site.register(EEL_Edition_Status, EEL_Edition_StatusAdmin)
admin.site.register(King, KingAdmin)
admin.site.register(Language, LanguageAdmin)
admin.site.register(Bib_Category, Bib_CategoryAdmin)
admin.site.register(Archive, ArchiveAdmin)
admin.site.register(Sigla_Provenance, Sigla_ProvenanceAdmin)
admin.site.register(Folio_Side, Folio_SideAdmin)
admin.site.register(Version_Relationship_Type, Version_Relationship_TypeAdmin)
admin.site.register(Version_Relationship, Version_RelationshipAdmin)
admin.site.register(Person, PersonAdmin)
admin.site.register(Place, PlaceAdmin)
admin.site.register(Topic, TopicAdmin)
admin.site.register(Hyparchetype, HyparchetypeAdmin)
admin.site.register(Resource, ResourceAdmin)
admin.site.register(User_Comment, User_CommentAdmin)
admin.site.unregister(User)
admin.site.register(User, UserAdmin)
