# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from admin_generic import *
from admin_custom import *
from django.contrib import admin


#
admin.site.register(Web_User, Web_UserAdmin)
admin.site.register(User_Directory, User_DirectoryAdmin)
