# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from django.contrib import admin

#
class Web_User_User_DirectoryInline(admin.TabularInline):

	model = Web_User_User_Directory
	extra = 1

#
class Web_UserAdmin(admin.ModelAdmin):
	model = Web_User

	verbose_name = 'Web User'
	verbose_name_plural = 'Web Users'

	inlines = (Web_User_User_DirectoryInline, )
	
	
#
class User_DirectoryAdmin(admin.ModelAdmin):
	model = User_Directory

	verbose_name = 'User Directory'
	verbose_name_plural = 'User Directories'

	inlines = (Web_User_User_DirectoryInline, )
	
	
	list_display = ('name', )
	search_fields = ['name', ]

#
